### ISSUE TITLE
请问这个弹幕的聊天，需要什么配置吗

### ISSUE THREAD

**Issue by HannahLihui** [zhanghuanhao/NebulaMOOC#16]
playvideo.js:116 WebSocket connection to 'wss://localhost:9080/websocket' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

**Comment by zhanghuanhao** [comment]
因为这个证书是用www.nebulamooc.top这个域名注册的，所以如果你用了wss去连接不能使用localhost，要在hosts里面配`www.nebulamooc.top 127.0.0.1`然后用这个域名去连接。

**Comment by HannahLihui** [comment]
感谢大佬，解决问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Walton"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 晚上6:14
收件人:&nbsp;"zhanghuanhao/NebulaMOOC"<NebulaMOOC@noreply.github.com&gt;;
抄送:&nbsp;"3303594461"<3303594461@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhanghuanhao/NebulaMOOC] 请问这个弹幕的聊天，需要什么配置吗 (#16)





 
因为这个证书是用www.nebulamooc.top这个域名注册的，所以如果你用了wss去连接不能使用localhost，要在hosts里面配www.nebulamooc.top 127.0.0.1然后用这个域名去连接。
