### ISSUE TITLE
求配套的前端项目

### ISSUE THREAD

**Issue by yangtao596739215** [zhanghuanhao/NebulaMOOC#19]
博主您好,我是一名在校大学生,看了您的项目以后,感受收益匪浅,很多东西都豁然开朗,文档也写的很清晰,但是,看归看,很想自己把这个项目实时部署,体验一番,所以想求一份前端的代码,感谢博主

**Comment by zhanghuanhao** [comment]
谢谢。部署文档放在extra目录下了，希望能帮到你。另外，我不知道你说的前端代码指的是什么，没理解错的话是Web代码，在这里 [Web代码](https://github.com/zhanghuanhao/NebulaMOOC/tree/master/web-server/src/main/resources/static)

**Comment by yangtao596739215** [comment]
> 谢谢。部署文档放在extra目录下了，希望能帮到你。另外，我不知道你说的前端代码指的是什么，没理解错的话是Web代码，在这里 [Web代码](https://github.com/zhanghuanhao/NebulaMOOC/tree/master/web-server/src/main/resources/static)

噢噢,好的,谢谢博主,是我自己没仔细看,感谢博主分享
